force-app/main/default/objects/AWS_Configuration__c/AWS_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AWS Configuration</label>
</CustomObject>

force-app/main/default/objects/AWS_Configuration__c/fields/Access_Key__c.field-meta.xml
<CustomField>
    <fullName>Access_Key__c</fullName>
    <label>Access Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/AWS_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Secret_Key__c</fullName>
    <label>AWS Secret Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Name__c</fullName>
    <label>Bucket Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Delete_after_Sync__c.field-meta.xml
<CustomField>
    <fullName>Delete_after_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete after Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Max_File_Size_Bytes__c.field-meta.xml
<CustomField>
    <fullName>Max_File_Size_Bytes__c</fullName>
    <label>Max File Size (Bytes)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CMT_AWSUploaderLWCTest.cls
/**
 * @description       : 
 * @author            : Ashwani Soni
 * @group             : 
 * @last modified on  : 07-19-2021
 * @last modified by  : Ashwani Soni
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   07-19-2021   Ashwani Soni   Initial Version
**/
@isTest
public with sharing class CMT_AWSUploaderLWCTest {
    
    @TestSetup
    static void makeData()
    {
        AWS_Configuration__c awsConfig = new AWS_Configuration__c();
        awsConfig.Enable_Sync__c = true;
        awsConfig.AWS_Secret_Key__c = 'VVV/erTYD';
        awsConfig.Access_Key__c = 'XXCDFRTFFF';
        awsConfig.Bucket_Name__c = 'printninjauat';
        awsConfig.Region__c = 'WERTHYGFD';
        awsConfig.Max_File_Size_Bytes__c = 50000;
        awsConfig.Delete_after_Sync__c = true;
        insert awsConfig;

        Account acc = new Account(Name='Some Account Pvt Ltd');
        insert acc;

        Contact con = new Contact(LastName='Some Contact', FirstName='User', AccountId=acc.Id);
        insert con;

        Task taskRecord = new Task(Subject='Herer Subject', WhatId=acc.Id, WhoId=con.id, OwnerId=UserInfo.getUserId(), Status='Not Started', Priority='Normal');
        insert taskRecord;

        Attachment attRecord = new Attachment();
        attRecord.Name = 'Some File Name.txt';
        attRecord.ContentType = 'plain/text';
        attRecord.ParentId = taskRecord.Id;
        attRecord.Body = Blob.valueOf('abcdarea');
        insert attRecord;
    }

    public static testmethod void testUpload() 
    {
        List<CMT_AWSUploaderLWC.UploadInfo> uploadInfo = CMT_AWSUploaderLWC.getAttachmentData();
        CMT_AWSUploaderLWC.getUploadConfiguration();
        CMT_AWSUploaderLWC.createLogicalLink(uploadInfo[0].attRecord.Id, null, 'fileUrl');
        CMT_AWSUploaderLWC.getAttachmentData();
    }
}