force-app/main/default/objects/AWS_Configuration__c/AWS_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AWS Configuration</label>
</CustomObject>

force-app/main/default/objects/AWS_Configuration__c/fields/Access_Key__c.field-meta.xml
<CustomField>
    <fullName>Access_Key__c</fullName>
    <label>Access Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/AWS_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Secret_Key__c</fullName>
    <label>AWS Secret Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Name__c</fullName>
    <label>Bucket Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Delete_after_Sync__c.field-meta.xml
<CustomField>
    <fullName>Delete_after_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete after Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Max_File_Size_Bytes__c.field-meta.xml
<CustomField>
    <fullName>Max_File_Size_Bytes__c</fullName>
    <label>Max File Size (Bytes)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/AWS_File__c.object-meta.xml
<CustomObject>
    <label>AWS File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AWS_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <inlineHelpText>Full Name of the file</inlineHelpText>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/fields/File_Url__c.field-meta.xml
<CustomField>
    <fullName>File_Url__c</fullName>
    <label>File Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CMT_FileViewLWCTest.cls
/**
 * @description       : 
 * @author            : Ashwani Soni
 * @group             : 
 * @last modified on  : 06-27-2021
 * @last modified by  : Ashwani Soni
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   06-27-2021   Ashwani Soni   Initial Version
**/
@isTest
public with sharing class CMT_FileViewLWCTest 
{
    @TestSetup
    static void makeData()
    {
        AWS_Configuration__c awsConfig = new AWS_Configuration__c();
        awsConfig.Enable_Sync__c = true;
        awsConfig.AWS_Secret_Key__c = 'VVV/erTYD';
        awsConfig.Access_Key__c = 'XXCDFRTFFF';
        awsConfig.Bucket_Name__c = 'printninjauat';
        awsConfig.Region__c = 'WERTHYGFD';
        awsConfig.Max_File_Size_Bytes__c = 50000;
        awsConfig.Delete_after_Sync__c = true;
        insert awsConfig;
        
        AWS_File__c fileRecord = new AWS_File__c();
        fileRecord.Name = 'Test';
        fileRecord.File_Name__c = 'Test.jpg';
        fileRecord.File_Url__c = CMT_AWSUtil.endpointStr+'/abc.jpg';
        fileRecord.External_ID__c = fileRecord.File_Url__c;
        fileRecord.OwnerId = UserInfo.getUserId();

        insert fileRecord;
    }

    public static testMethod void generateURL() 
    {
        CMT_FileViewLWC.generateFilePreview(CMT_AWSUtil.endpointStr+'/abc.jpg');
    }

}