force-app/main/default/objects/AWS_Configuration__c/AWS_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AWS Configuration</label>
</CustomObject>

force-app/main/default/objects/AWS_Configuration__c/fields/Access_Key__c.field-meta.xml
<CustomField>
    <fullName>Access_Key__c</fullName>
    <label>Access Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/AWS_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Secret_Key__c</fullName>
    <label>AWS Secret Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Name__c</fullName>
    <label>Bucket Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Delete_after_Sync__c.field-meta.xml
<CustomField>
    <fullName>Delete_after_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete after Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__c/fields/Max_File_Size_Bytes__c.field-meta.xml
<CustomField>
    <fullName>Max_File_Size_Bytes__c</fullName>
    <label>Max File Size (Bytes)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CMT_AWSUploadAndSyncBatchTest.cls
/**
 * @description       : 
 * @author            : Ashwani Soni
 * @group             : 
 * @last modified on  : 07-19-2021
 * @last modified by  : Ashwani Soni
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   06-27-2021   Ashwani Soni   Initial Version
**/
@isTest
public with sharing class CMT_AWSUploadAndSyncBatchTest 
{
    @TestSetup
    static void makeData()
    {
        AWS_Configuration__c awsConfig = new AWS_Configuration__c();
        awsConfig.Enable_Sync__c = true;
        awsConfig.AWS_Secret_Key__c = 'VVV/erTYD';
        awsConfig.Access_Key__c = 'XXCDFRTFFF';
        awsConfig.Bucket_Name__c = 'printninjauat';
        awsConfig.Region__c = 'WERTHYGFD';
        awsConfig.Max_File_Size_Bytes__c = 50000;
        awsConfig.Delete_after_Sync__c = true;
        insert awsConfig;

        Account acc = new Account(Name='Some Account Pvt Ltd');
        insert acc;

        Contact con = new Contact(LastName='Some Contact', FirstName='User', AccountId=acc.Id);
        insert con;

        Task taskRecord = new Task(Subject='Herer Subject', WhatId=acc.Id, WhoId=con.id, OwnerId=UserInfo.getUserId(), Status='Not Started', Priority='Normal');
        insert taskRecord;

        Attachment attRecord = new Attachment();
        attRecord.Name = 'Some File Name.txt';
        attRecord.ContentType = 'plain/text';
        attRecord.ParentId = taskRecord.Id;
        attRecord.Body = Blob.valueOf('abcdarea');
        insert attRecord;
    }
    public static testMethod void uploadSuccess() 
    {
        CMT_AWSMockHTTP httpMock = new CMT_AWSMockHTTP();

        Attachment attRecord = [SELECT id, Name, ParentId, Body, ContentType FROM Attachment LIMIT 1];
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, httpMock);
            CMT_AWSUploadAndSyncBatch batch = new CMT_AWSUploadAndSyncBatch();
            Database.executeBatch(batch,1);
        Test.stopTest();
    }

    public static testMethod void uploadFail() 
    {
        CMT_AWSMockHTTP httpMock = new CMT_AWSMockHTTP();
        CMT_AWSMockHTTP.state = 2;

        Attachment attRecord = [SELECT id, Name, ParentId, Body, ContentType FROM Attachment LIMIT 1];
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, httpMock);
            CMT_AWSUploadAndSyncBatch batch = new CMT_AWSUploadAndSyncBatch();
            Database.executeBatch(batch,1);
        Test.stopTest();
    }

    public static testMethod void uploadSuccessNoDelete() 
    {
        CMT_AWSMockHTTP httpMock = new CMT_AWSMockHTTP();

        AWS_Configuration__c awsConfig = [SELECT id FROM AWS_Configuration__c LIMIT 1];
        awsConfig.Delete_after_Sync__c = false;
        update awsConfig;

        Attachment attRecord = [SELECT id, Name, ParentId, Body, ContentType FROM Attachment LIMIT 1];
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, httpMock);
            CMT_AWSUploadAndSyncBatch batch = new CMT_AWSUploadAndSyncBatch();
            Database.executeBatch(batch,1);
        Test.stopTest();
    }

    public static testMethod void uploadSuccessNoDeleteSchedule() 
    {
        CMT_AWSMockHTTP httpMock = new CMT_AWSMockHTTP();

        AWS_Configuration__c awsConfig = [SELECT id FROM AWS_Configuration__c LIMIT 1];
        awsConfig.Delete_after_Sync__c = false;
        update awsConfig;

        Attachment attRecord = [SELECT id, Name, ParentId, Body, ContentType FROM Attachment LIMIT 1];
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, httpMock);
            CMT_AWSUploadAndSyncBatch schedulable = new CMT_AWSUploadAndSyncBatch();
            System.schedule('jobNameNEVERREPEAT004', '0 0 0 3 9 ? 2022', schedulable);
        Test.stopTest();
    }

    public static testMethod void deleteOnly() 
    {
        AWS_Configuration__c awsConfig = [SELECT id FROM AWS_Configuration__c LIMIT 1];
        awsConfig.Delete_after_Sync__c = false;
        update awsConfig;

        Attachment attRecord = [SELECT id, Name, ParentId, Body, ContentType FROM Attachment LIMIT 1];
        Test.startTest();
            CMT_AWSUploadAndSyncBatch batch = new CMT_AWSUploadAndSyncBatch();
            batch.mode = 'DELETE';
            Database.executeBatch(batch,1);
        Test.stopTest();
    }
}