force-app/main/default/objects/Game_Quote__c/Game_Quote__c.object-meta.xml
<CustomObject>
    <label>Game Quote (Old)</label>
    <nameField>
        <label>Game Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Quotes (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Quote__c/fields/Additional_charge_s_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_charge_s_1__c</fullName>
    <description>Additional charges that apply to order</description>
    <label>Additional Charge(s)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Additional_charge_s_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_charge_s_2__c</fullName>
    <description>Additional charges that apply to order</description>
    <label>Additional Charge(s)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Assembly_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Assembly_Cost_1__c</fullName>
    <description>Cost of assembling Quantity 1</description>
    <inlineHelpText>Cost of assembling Quantity 1</inlineHelpText>
    <label>Assembly Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Assembly_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Assembly_Cost_2__c</fullName>
    <description>Cost of assembling Quantity 2</description>
    <inlineHelpText>Cost of assembling Quantity 2</inlineHelpText>
    <label>Assembly Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Expedited_Freight_1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_1__c</fullName>
    <description>Cost (pre-markup) of expedited portion of shipping</description>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Expedited_Freight_2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_2__c</fullName>
    <description>Cost (pre-markup) of expedited portion of shipping</description>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Expedited_Freight_Markup_i1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Markup_i1__c</fullName>
    <description>Markup (percentage) to be added to order&apos;s related expedited freight costs</description>
    <inlineHelpText>Markup (percentage) to be added to order&apos;s related expedited freight costs</inlineHelpText>
    <label>Expedited Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Expedited_Freight_Markup_i2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Markup_i2__c</fullName>
    <description>Markup (percentage) to be added to order&apos;s related expedited freight costs</description>
    <label>Expedited Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Expedited_Quantity_1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Quantity_1__c</fullName>
    <description>Quantity of order that should be shipped via expedited shipping</description>
    <label>Expedited Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Expedited_Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Quantity_2__c</fullName>
    <description>Quantity of order that should be shipped via expedited shipping</description>
    <label>Expedited Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/gq_shiptocity__c.field-meta.xml
<CustomField>
    <fullName>gq_shiptocity__c</fullName>
    <label>Ship To City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/gq_shiptocountry__c.field-meta.xml
<CustomField>
    <fullName>gq_shiptocountry__c</fullName>
    <description>Country of shipping address</description>
    <label>Ship To Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/gq_shiptostate__c.field-meta.xml
<CustomField>
    <fullName>gq_shiptostate__c</fullName>
    <label>Ship To State / Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/gq_shiptostreet__c.field-meta.xml
<CustomField>
    <fullName>gq_shiptostreet__c</fullName>
    <label>Ship To Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/gq_shiptozip__c.field-meta.xml
<CustomField>
    <fullName>gq_shiptozip__c</fullName>
    <label>Ship To Zip / Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Grd_Freight_1__c.field-meta.xml
<CustomField>
    <fullName>Grd_Freight_1__c</fullName>
    <description>Cost (pre-markup) of ground portion of shipping</description>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Grd_Freight_2__c.field-meta.xml
<CustomField>
    <fullName>Grd_Freight_2__c</fullName>
    <description>Cost (pre-markup) of ground portion of shipping</description>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Ground_Freight_Markup_i1__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Markup_i1__c</fullName>
    <description>Markup (percentage) to be added to order&apos;s related ground freight cost</description>
    <label>Ground Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Ground_Freight_Markup_i2__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Markup_i2__c</fullName>
    <description>Markup (percentage) to be added to order&apos;s related ground freight cost</description>
    <label>Ground Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/newshipping_residential__c.field-meta.xml
<CustomField>
    <fullName>newshipping_residential__c</fullName>
    <description>Indicates whether or not shipping address is a residential property.</description>
    <label>Residential Address?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Ocean_Freight_1__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_1__c</fullName>
    <description>Cost (pre-markup) of ocean freight shipping</description>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Ocean_Freight_2__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_2__c</fullName>
    <description>Cost (pre-markup) of ocean freight shipping</description>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Ocean_Freight_Markup_i1__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Markup_i1__c</fullName>
    <description>Markup to be aded to order&apos;s related quoted price</description>
    <label>Ocean Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Ocean_Freight_Markup_i2__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Markup_i2__c</fullName>
    <description>Markup to be aded to order&apos;s related quoted price</description>
    <label>Ocean Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Game_Quotes_del</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Product_Purchase_Markup1__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchase_Markup1__c</fullName>
    <description>Markup (percentage) to be added to order&apos;s related product purchase cost</description>
    <inlineHelpText>Markup (percentage) to be added to order&apos;s related product purchase cost</inlineHelpText>
    <label>Product Purchase Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Product_Purchase_Markup2__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchase_Markup2__c</fullName>
    <description>Markup (percentage) to be added to order&apos;s related product purchase cost</description>
    <label>Product Purchase Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Prototyping_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Prototyping_Cost_1__c</fullName>
    <description>Cost of prototyping Quantity 1</description>
    <inlineHelpText>Cost of prototyping Quantity 1</inlineHelpText>
    <label>Prototyping Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Prototyping_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Prototyping_Cost_2__c</fullName>
    <description>Cost of prototyping Quantity 2</description>
    <inlineHelpText>Cost of prototyping Quantity 2</inlineHelpText>
    <label>Prototyping Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Quote_From_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Quote_From_Calculator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box will be checked if a game quote came through from the game calculator (some day)</description>
    <inlineHelpText>This box will be checked if a game quote came through from the game calculator (some day)</inlineHelpText>
    <label>Quote From Calculator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Tax_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_1__c</fullName>
    <description>Tax to be added to order&apos;s related quoted price</description>
    <inlineHelpText>Tax, in USD, to be applied to order&apos;s related quoted price</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Tax_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_2__c</fullName>
    <description>Tax to be added to order&apos;s related quoted price</description>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Total_Quantity_1__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_1__c</fullName>
    <description>Order quantity after overuns are added</description>
    <inlineHelpText>Order quantity after overuns are added</inlineHelpText>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Total_Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_2__c</fullName>
    <description>Order quantity after overuns are added</description>
    <inlineHelpText>Order quantity after overuns are added</inlineHelpText>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Use_to_Calculate_ROW_1__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_1__c</fullName>
    <description>Signifies quote that is selected for ROW</description>
    <label>Use To Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Use_to_Calculate_ROW_2__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_2__c</fullName>
    <description>Signifies which quote is selected for ROW</description>
    <label>Use To Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GameQuoteHelpertest.cls
@isTest(seeAllData=true)
public class GameQuoteHelpertest{
    public static testMethod void testGameQuotehelper(){
    test.startTest();
        Account acc=new Account(
            Name='Doom'
        );
        insert acc;
        
        Contact c=new Contact(
         LastName='Marial',
         AccountId=acc.Id
   
        );
        insert c;
        Opportunity opp=new Opportunity(
         Name='Doomstone',
         CloseDate=Date.today(),
         Opportunity_Vendor__c='International',
         StageName='Draft',
         AccountId=acc.Id,
         Probability=0
         
        );
          
        insert opp; 
    
        Game_Quote__c q=new Game_Quote__c(
            Name='gamequote',
            Use_to_Calculate_ROW_1__c='Yes',
            Opportunity__c=opp.id,
            gq_shiptostreet__c='123 Penny Lane',
            gq_shiptocity__c='Skevanston',
            gq_shiptostate__c='IL',
            gq_shiptozip__c='60201',
            gq_shiptocountry__c='USA',
            newshipping_residential__c='Yes',
            Assembly_Cost_1__c=0,
            Quote_From_Calculator__c = FALSE,
            Total_Quantity_1__c=12,
            Expedited_Quantity_1__c=16,
            Product_Purchase_Markup1__c=24,
            Ocean_Freight_1__c=2093,
            Ocean_Freight_Markup_i1__c=293,
            Tax_1__c=23940,
            Grd_Freight_1__c=233,
            Ground_Freight_Markup_i1__c=390,
            Expedited_Freight_1__c=2409,
            Expedited_Freight_Markup_i1__c=20,
            Additional_charge_s_1__c=2093,
            Prototyping_Cost_1__c=293.00,
            Assembly_Cost_2__c=0,
            Total_Quantity_2__c=12,
            Expedited_Quantity_2__c=16,
            Product_Purchase_Markup2__c=24,
            Ocean_Freight_2__c=2093,
            Ocean_Freight_Markup_i2__c=293,
            Tax_2__c=23940,
            Grd_Freight_2__c=233,
            Ground_Freight_Markup_i2__c=390,
            Expedited_Freight_2__c=2409,
            Expedited_Freight_Markup_i2__c=20,
            Additional_charge_s_2__c=2093,
            Prototyping_Cost_2__c=293.00
            
        );
        
        insert q;    
        
        Game_Quote__c r=new Game_Quote__c(
            Name='secondgamequote',
            Opportunity__c=opp.id
            
            
        );
        
        insert r;  
       
        q.Use_to_Calculate_ROW_1__c='No';
        q.Use_to_Calculate_ROW_2__c='Yes';
       
           update q;
         update opp;
        q.Use_to_Calculate_ROW_1__c='Yes';
        q.Use_to_Calculate_ROW_2__c='No';
       
           update q;
        
        opp.StageName='Closed Won';
        opp.Production_Status__c='Waiting For Artwork';
         update opp;
        
        q.Use_to_Calculate_ROW_1__c='No';
        q.Use_to_Calculate_ROW_2__c='Yes';
       
           update q;
        
        opp.StageName='Closed Won';
        opp.Production_Status__c='Ready For Proofing';
         update opp;
         
        test.stopTest();
    }
    
    public static testMethod void testOpportunityHelper(){
        test.startTest();
         Account acc=new Account(
            Name='Doom'
        );
        insert acc;
        
        Contact c=new Contact(
         LastName='Marial',
         AccountId=acc.Id
   
        );
        insert c;
        Opportunity opp=new Opportunity(
         Name='Doomstone',
         CloseDate=Date.today(),
         Opportunity_Vendor__c='International',
         StageName='Draft',
         AccountId=acc.Id
         
        );
          
        insert opp; 
       
       
        
        Opportunity quote=new OpportunityHelper().getByOpportunity(opp.Id);
        Opportunity opp11=new OpportunityHelper().getByJobNumber(''+quote.Job_Number1__c);
       // new OpportunityHelper().setTaskByOppStage(opp11.Id,'Draft');
        //new OpportunityHelper().setTaskByOppStage(opp11.Id,'Quoted by China');
        //new OpportunityHelper().setTaskByOppStage(opp11.Id,'Proposal/ Custom Quote');
       // new OpportunityHelper().setTaskByOppStage(opp11.Id,'Proposal/ Online Blind Quote');
       // opp11.StageName='Draft';
       // update opp11;
       // opp11.StageName='Quoted by China';
       // update opp11;
       // opp11.StageName='Proposal/ Custom Quote';
       // update opp11;
        
       // opp11.StageName='Proposal/ Online Blind Quote';
       // update opp11;
        test.stopTest();
    }
    
    public static testMethod void testContactHelper(){
        test.startTest();
         Account acc=new Account(
            Name='Doom'
        );
        insert acc;
        
        Contact c=new Contact(
         LastName='Marial',
         AccountId=acc.Id,
          Is_Primary__c=true
   
        );
        
        Contact c1=new Contact(
         LastName='Marial12',
         AccountId=acc.Id
        
        );
        insert c;
        insert c1;
        Contact quote=ContactHelper.getPrimaryContactByAccount(acc.Id);
        test.stopTest();
    }
    
}