force-app/main/default/objects/Custom_Game_Quote__c/Custom_Game_Quote__c.object-meta.xml
<CustomObject>
    <description>Quote form for custom card and board games.</description>
    <label>Game Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Additional_Charges_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charges_1__c</fullName>
    <label>Additional Charge(s)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Additional_Charges_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charges_2__c</fullName>
    <label>Additional Charge(s)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Assembly_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Assembly_Cost_1__c</fullName>
    <label>Assembly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Assembly_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Assembly_Cost_2__c</fullName>
    <label>Assembly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Cost_1__c</fullName>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Cost_2__c</fullName>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Quantity_1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Quantity_1__c</fullName>
    <label>Expedited Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Quantity_2__c</fullName>
    <label>Expedited Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Cost_1__c</fullName>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Cost_2__c</fullName>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Cost_1__c</fullName>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Cost_2__c</fullName>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Game_Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Order_Quantity_1__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity_1__c</fullName>
    <inlineHelpText>Quantity ordered by the customer</inlineHelpText>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Order_Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity_2__c</fullName>
    <inlineHelpText>Quantity ordered by the customer</inlineHelpText>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Prototyping_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Prototyping_Cost_1__c</fullName>
    <label>Prototyping Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Prototyping_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Prototyping_Cost_2__c</fullName>
    <label>Prototyping Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Quote_From_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Quote_From_Calculator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote From Calculator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Residential_Address__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address__c</fullName>
    <label>Residential Address?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_City__c</fullName>
    <label>Ship To City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ship_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Country__c</fullName>
    <label>Ship To Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ship_To_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_State_Province__c</fullName>
    <label>Ship To State / Province</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ship_To_Street__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Street__c</fullName>
    <label>Ship To Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ship_To_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Zip_Postal_Code__c</fullName>
    <label>Ship To Zip / Postal Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Tax_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_1__c</fullName>
    <inlineHelpText>10% for all orders shipped to Illinois</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Tax_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_2__c</fullName>
    <inlineHelpText>10% for all orders shipped to Illinois</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_1__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_1__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_2__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_2__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomGameQuoteHelpertest.cls
@isTest(seeAllData=true)
public class CustomGameQuoteHelpertest{
    public static testMethod void testCustomGameQuotehelper(){
    test.startTest();
        Account acc=new Account(
            Name='Wally'
        );
        insert acc;
        
        Contact c=new Contact(
         LastName='West',
         AccountId=acc.Id
   
        );
        insert c;
        Opportunity opp=new Opportunity(
         Name='Rebirth',
         CloseDate=Date.today(),
         Opportunity_Vendor__c='International',
         StageName='Draft',
         AccountId=acc.Id,
         Probability=0
         
        );
          
        insert opp; 
    
        Custom_Game_Quote__c q=new Custom_Game_Quote__c(
            Name='bestgameever',
            Use_to_Calculate_ROW_1__c='Yes',
            Opportunity__c=opp.id,
            Ship_To_Street__c='123 Flash St',
            Ship_To_City__c='Keystone City',
            Ship_To_State_Province__c='KS',
            Ship_To_Zip_Postal_Code__c='67003',
            Ship_To_Country__c='United States',
            Residential_Address__c='Yes',
            Assembly_Cost_1__c=0,
            Quote_From_Calculator__c = FALSE,
            Order_Quantity_1__c=12,
            Expedited_Quantity_1__c=16,
            Ocean_Freight_Cost_1__c=2093,
            Tax_1__c=23940,
            Ground_Freight_Cost_1__c=233,
            Expedited_Freight_Cost_1__c=2409,
            Additional_charges_1__c=2093,
            Prototyping_Cost_1__c=293.00,
            Assembly_Cost_2__c=0,
            Order_Quantity_2__c=12,
            Expedited_Quantity_2__c=16,
            Ocean_Freight_Cost_2__c=2093,
            Tax_2__c=23940,
            Ground_Freight_Cost_2__c=233,
            Expedited_Freight_Cost_2__c=2409,
            Additional_charges_2__c=2093,
            Prototyping_Cost_2__c=293.00
            
        );
        
        insert q;    
        
        Custom_Game_Quote__c r=new Custom_Game_Quote__c(
            Name='anokaygame',
            Opportunity__c=opp.id
            
            
        );
        
        insert r;  
       
        q.Use_to_Calculate_ROW_1__c='No';
        q.Use_to_Calculate_ROW_2__c='Yes';
       
           update q;
         update opp;
        q.Use_to_Calculate_ROW_1__c='Yes';
        q.Use_to_Calculate_ROW_2__c='No';
       
           update q;
        
        opp.StageName='Closed Won';
        opp.Production_Status__c='Waiting For Artwork';
         update opp;
        
        q.Use_to_Calculate_ROW_1__c='No';
        q.Use_to_Calculate_ROW_2__c='Yes';
       
           update q;
        
        opp.StageName='Closed Won';
        opp.Production_Status__c='Ready For Proofing';
         update opp;
         
        test.stopTest();
    }
    
    public static testMethod void testOpportunityHelper(){
        test.startTest();
         Account acc=new Account(
            Name='Wally'
        );
        insert acc;
        
        Contact c=new Contact(
         LastName='West',
         AccountId=acc.Id
   
        );
        insert c;
        Opportunity opp=new Opportunity(
         Name='Rebirth',
         CloseDate=Date.today(),
         Opportunity_Vendor__c='International',
         StageName='Draft',
         AccountId=acc.Id
         
        );
          
        insert opp; 
       
       
        
        Opportunity quote=new OpportunityHelper().getByOpportunity(opp.Id);
        Opportunity opp11=new OpportunityHelper().getByJobNumber(''+quote.Job_Number1__c);
       // new OpportunityHelper().setTaskByOppStage(opp11.Id,'Draft');
        //new OpportunityHelper().setTaskByOppStage(opp11.Id,'Quoted by China');
        //new OpportunityHelper().setTaskByOppStage(opp11.Id,'Proposal/ Custom Quote');
       // new OpportunityHelper().setTaskByOppStage(opp11.Id,'Proposal/ Online Blind Quote');
       // opp11.StageName='Draft';
       // update opp11;
       // opp11.StageName='Quoted by China';
       // update opp11;
       // opp11.StageName='Proposal/ Custom Quote';
       // update opp11;
        
       // opp11.StageName='Proposal/ Online Blind Quote';
       // update opp11;
        test.stopTest();
    }
    
    public static testMethod void testContactHelper(){
        test.startTest();
         Account acc=new Account(
            Name='Wally'
        );
        insert acc;
        
        Contact c=new Contact(
         LastName='West',
         AccountId=acc.Id,
          Is_Primary__c=true
   
        );
        
        Contact c1=new Contact(
         LastName='West12',
         AccountId=acc.Id
        
        );
        insert c;
        insert c1;
        Contact quote=ContactHelper.getPrimaryContactByAccount(acc.Id);
        test.stopTest();
    }
    
}