force-app/main/default/objects/Custom_Game_Quote__c/Custom_Game_Quote__c.object-meta.xml
<CustomObject>
    <description>Quote form for custom card and board games.</description>
    <label>Game Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Cost_1__c</fullName>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Cost_2__c</fullName>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Cost_3__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Cost_3__c</fullName>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Cost_4__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Cost_4__c</fullName>
    <label>Expedited Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Markup_1__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Markup_1__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Expedited Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Markup_2__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Markup_2__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Expedited Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Markup_3__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Markup_3__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Expedited Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Expedited_Freight_Markup_4__c.field-meta.xml
<CustomField>
    <fullName>Expedited_Freight_Markup_4__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Expedited Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Cost_1__c</fullName>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Cost_2__c</fullName>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Cost_3__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Cost_3__c</fullName>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Cost_4__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Cost_4__c</fullName>
    <label>Ground Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Markup_1__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Markup_1__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ground Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Markup_2__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Markup_2__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ground Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Markup_3__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Markup_3__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ground Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ground_Freight_Markup_4__c.field-meta.xml
<CustomField>
    <fullName>Ground_Freight_Markup_4__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ground Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Is_Used_To_Calculate_ROW__c.field-meta.xml
<CustomField>
    <fullName>Is_Used_To_Calculate_ROW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Used To Calculate ROW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Cost_1__c</fullName>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Cost_2__c</fullName>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Cost_3__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Cost_3__c</fullName>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Cost_4__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Cost_4__c</fullName>
    <label>Ocean Freight Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Markup_1__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Markup_1__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ocean Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Markup_2__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Markup_2__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ocean Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Markup_3__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Markup_3__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ocean Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Ocean_Freight_Markup_4__c.field-meta.xml
<CustomField>
    <fullName>Ocean_Freight_Markup_4__c</fullName>
    <inlineHelpText>For custom quote only, website prices include markup.</inlineHelpText>
    <label>Ocean Freight Markup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <formula>Opportunity__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Quote_From_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Quote_From_Calculator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote From Calculator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Tax_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_1__c</fullName>
    <inlineHelpText>10% for all orders shipped to Illinois</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Tax_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_2__c</fullName>
    <inlineHelpText>10% for all orders shipped to Illinois</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Tax_3__c.field-meta.xml
<CustomField>
    <fullName>Tax_3__c</fullName>
    <inlineHelpText>10% for all orders shipped to Illinois</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Tax_4__c.field-meta.xml
<CustomField>
    <fullName>Tax_4__c</fullName>
    <inlineHelpText>10% for all orders shipped to Illinois</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_1__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_1__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_2__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_2__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_3__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_3__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_4__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_4__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomGameQuoteTriggerHandler.cls
public with sharing class CustomGameQuoteTriggerHandler {
    /**
     * Method called on before insert
     */
    public static void onBeforeInsert(list<Custom_Game_Quote__c> newRecords) {
        //Iterate Quote
        map<string, list<Custom_Game_Quote__c>> oppQuoteMap = new map<string, list<Custom_Game_Quote__c>>();
        for(Custom_Game_Quote__c quote: newRecords){
        	if(quote.OpportunityId__c != null){
	            oppQuoteMap.put(quote.OpportunityId__c, new list<Custom_Game_Quote__c>());
        	}
        }
        
        for(Custom_Game_Quote__c cgq: [SELECT OpportunityId__c, Use_to_Calculate_ROW_1__c, Use_to_Calculate_ROW_2__c, Use_to_Calculate_ROW_3__c, Use_to_Calculate_ROW_4__c FROM Custom_Game_Quote__c WHERE OpportunityId__c IN: oppQuoteMap.keySet()]){
        	oppQuoteMap.get(cgq.OpportunityId__c).add(cgq);
        }
        
        //Re-Iterate Quote
        for(Custom_Game_Quote__c quote: newRecords){
            Integer existingCount = (oppQuoteMap.containsKey(quote.OpportunityId__c) ? calRowExistingQuote(oppQuoteMap.get(quote.OpportunityId__c)) : 0);
            Integer currentCount = calRowCurrentQuote(quote);
            Integer totalCount = existingCount + currentCount;
            if(totalCount > 1){
                quote.addError('Only one quote combination can be used to calculate ROW for each Opportunity');
            }
            quote.Is_Used_To_Calculate_Row__c = (currentCount == 1 ? true : false);
            
            if(quote.Quote_From_Calculator__c != TRUE){
                quote.Ground_Freight_Cost_1__c = null;
                quote.Ground_Freight_Cost_2__c = null;
                quote.Ground_Freight_Cost_3__c = null;
                quote.Ground_Freight_Cost_4__c = null;
                quote.Ground_Freight_Markup_1__c =null;
                quote.Ground_Freight_Markup_2__c =null;
                quote.Ground_Freight_Markup_3__c =null;
                quote.Ground_Freight_Markup_4__c =null;
                quote.Tax_1__c = null;
                quote.Tax_2__c = null;
                quote.Tax_3__c = null;
                quote.Tax_4__c = null;
                quote.Ocean_Freight_Cost_1__c = null;
                quote.Ocean_Freight_Cost_2__c = null;
                quote.Ocean_Freight_Cost_3__c = null;
                quote.Ocean_Freight_Cost_4__c = null;
                quote.Ocean_Freight_Markup_1__c = null;
                quote.Ocean_Freight_Markup_2__c = null;
                quote.Ocean_Freight_Markup_3__c = null;
                quote.Ocean_Freight_Markup_4__c = null;
                quote.Expedited_Freight_Cost_1__c = null;
                quote.Expedited_Freight_Cost_2__c = null;
                quote.Expedited_Freight_Cost_3__c = null;
                quote.Expedited_Freight_Cost_4__c = null;
                quote.Expedited_Freight_Markup_1__c = null;
                quote.Expedited_Freight_Markup_2__c = null;
                quote.Expedited_Freight_Markup_3__c = null;
                quote.Expedited_Freight_Markup_4__c = null;
            } 
        }
    }
    
    /**
     * Method called on before update
     */
    public static void onBeforeUpdate(list<Custom_Game_Quote__c> newRecords, map<Id, Custom_Game_Quote__c> oldRecordMap) {        
        //Iterate Quote
        set<string> setCurrentQuoteIds = new set<string>();
        map<string, list<Custom_Game_Quote__c>> oppQuoteMap = new map<string, list<Custom_Game_Quote__c>>();
        for(Custom_Game_Quote__c quote: newRecords){
        	if(quote.OpportunityId__c != null){
	            setCurrentQuoteIds.add(quote.Id);
	            oppQuoteMap.put(quote.OpportunityId__c, new list<Custom_Game_Quote__c>());
        	}
        }
        
        for(Custom_Game_Quote__c cgq: [SELECT OpportunityId__c, Use_to_Calculate_ROW_1__c, Use_to_Calculate_ROW_2__c, Use_to_Calculate_ROW_3__c, Use_to_Calculate_ROW_4__c FROM Custom_Game_Quote__c WHERE Id NOT IN: setCurrentQuoteIds AND OpportunityId__c IN: oppQuoteMap.keySet()]){
        	oppQuoteMap.get(cgq.OpportunityId__c).add(cgq);
        }
        
        //Re-Iterate Quote
        for(Custom_Game_Quote__c quote: newRecords){
        	Integer existingCount = (oppQuoteMap.containsKey(quote.OpportunityId__c) ? calRowExistingQuote(oppQuoteMap.get(quote.OpportunityId__c)) : 0);
            Integer currentCount = calRowCurrentQuote(quote);
            Integer totalCount = existingCount + currentCount;
            if(totalCount > 1){
                quote.addError('Only one quote combination can be used to calculate ROW for each Opportunity');
            }
            quote.Is_Used_To_Calculate_Row__c = (currentCount == 1 ? true : false); 
        }
    }
    
    //Method to calculate Row Existing Quote
    public static integer calRowExistingQuote(list<Custom_Game_Quote__c> existingQuote){
        Integer countSet =  0;
        for(Custom_Game_Quote__c quote: existingQuote){
	        if(quote.Use_to_Calculate_ROW_1__c == 'Yes'){
	            countSet++;
	        }
	        if(quote.Use_to_Calculate_ROW_2__c == 'Yes'){
	            countSet++;
	        }
	        if(quote.Use_to_Calculate_ROW_3__c == 'Yes'){
	            countSet++;
	        }
	        if(quote.Use_to_Calculate_ROW_4__c == 'Yes'){
	            countSet++;
	        }
        }
        return countSet;
    }
    
    //Method to calculate Row Current Quote
    public static integer calRowCurrentQuote(Custom_Game_Quote__c quote){
        Integer countSet =  0;
        if(quote.Use_to_Calculate_ROW_1__c == 'Yes'){
            countSet++;
        }
        if(quote.Use_to_Calculate_ROW_2__c == 'Yes'){
            countSet++;
        }
        if(quote.Use_to_Calculate_ROW_3__c == 'Yes'){
            countSet++;
        }
        if(quote.Use_to_Calculate_ROW_4__c == 'Yes'){
            countSet++;
        }
        return countSet;
    }
}