force-app/main/default/objects/Custom_Game_Quote__c/Custom_Game_Quote__c.object-meta.xml
<CustomObject>
    <description>Quote form for custom card and board games.</description>
    <label>Game Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_1__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_1__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_2__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_2__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_3__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_3__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Use_to_Calculate_ROW_4__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_4__c</fullName>
    <inlineHelpText>Indicates which quantity customer has ordered</inlineHelpText>
    <label>Use to Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game_Quote__c/Game_Quote__c.object-meta.xml
<CustomObject>
    <label>Game Quote (Old)</label>
    <nameField>
        <label>Game Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Quotes (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Quote__c/fields/Use_to_Calculate_ROW_1__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_1__c</fullName>
    <description>Signifies quote that is selected for ROW</description>
    <label>Use To Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game_Quote__c/fields/Use_to_Calculate_ROW_2__c.field-meta.xml
<CustomField>
    <fullName>Use_to_Calculate_ROW_2__c</fullName>
    <description>Signifies which quote is selected for ROW</description>
    <label>Use To Calculate ROW</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UtilityController.cls
public with sharing class UtilityController {
    public static list<sObject> returnQuoteListRecords(string objectAPIName, string filterFieldAPIName, set<string> filterIds){
        string allFields = '';
        set<string> ignoreFields = new set<string>{'LastReferencedDate', 'LastViewedDate'};
        
        map<String, Schema.SObjectField> fieldObjMap = Schema.getGlobalDescribe().get(objectAPIName).getDescribe().fields.getMap();
        for(Schema.SObjectField s : fieldObjMap.values()){
        	if(!ignoreFields.contains(s.getDescribe().getName())){
            	allFields += (allFields == ''? '' : ',') + s.getDescribe().getName();
        	}
        }
        
        String soql_query = 'SELECT ' + allFields + ' FROM ' + objectAPIName + ' WHERE ' + filterFieldAPIName + ' IN : filterIds';
        
        if(objectAPIName == 'Quote'){
        	soql_query += ' AND (Use_to_Calculate_ROW_1__c = \'Yes\' OR Use_to_Calculate_ROW_2__c = \'Yes\' OR Use_to_Calculate_ROW_3__c = \'Yes\' OR Use_to_Calculate_ROW_4__c = \'Yes\' OR Use_to_Calculate_ROW_11__c = \'Yes\' OR Use_to_Calculate_ROW_12__c = \'Yes\' OR Use_to_Calculate_ROW_13__c = \'Yes\' OR Use_to_Calculate_ROW_14__c = \'Yes\')';
        }else if(objectAPIName == 'Game_Quote__c'){
        	soql_query += ' AND (Use_to_Calculate_ROW_1__c = \'Yes\' OR Use_to_Calculate_ROW_2__c = \'Yes\')';
        }else if(objectAPIName == 'Custom_Game_Quote__c'){
        	soql_query += ' AND (Use_to_Calculate_ROW_1__c = \'Yes\' OR Use_to_Calculate_ROW_2__c = \'Yes\' OR Use_to_Calculate_ROW_3__c = \'Yes\' OR Use_to_Calculate_ROW_4__c = \'Yes\')';
        }
        
        list<sObject> listSobject = Database.query(soql_query);
        return listSobject;
    }
}