force-app/main/default/objects/Custom_Game_Quote__c/Custom_Game_Quote__c.object-meta.xml
<CustomObject>
    <description>Quote form for custom card and board games.</description>
    <label>Game Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Game_Quote__c/fields/Product_Purchase_Cost1__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchase_Cost1__c</fullName>
    <description>OBSOLETE</description>
    <label>Product Purchase Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Components__c/Game_Components__c.object-meta.xml
<CustomObject>
    <label>Game Component</label>
    <nameField>
        <label>Game Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Components__c/fields/Component_Purchase_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Component_Purchase_Cost_1__c</fullName>
    <inlineHelpText>Purchase cost of component for Q1</inlineHelpText>
    <label>Component Purchase Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Game_Components__c/fields/Custom_Game_Quote__c.field-meta.xml
<CustomField>
    <fullName>Custom_Game_Quote__c</fullName>
    <label>Custom Game Quote</label>
    <referenceTo>Custom_Game_Quote__c</referenceTo>
    <relationshipName>Game_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GameComponentsTriggerHandler.cls
public with sharing class GameComponentsTriggerHandler{
    /**
     * Method called on after insert
     */
    public static void onAfterInsert(list<Game_Components__c> newRecords) {
        /*set<string> setGcId = new set<string>();
        for(Game_Components__c gc: newRecords){
            if(gc.Custom_Game_Quote__c != null && gc.Component_Purchase_Cost_1__c != null){
                setGcId.add(gc.Custom_Game_Quote__c);
            }
        }
        
        if(setGcId.size() > 0){
            list<Custom_Game_Quote__c> customGameQuotes = new list<Custom_Game_Quote__c>();
            for(Custom_Game_Quote__c cgq: [SELECT Id, Product_Purchase_Cost1__c, (SELECT Component_Purchase_Cost_1__c FROM Game_Components__r) FROM Custom_Game_Quote__c WHERE Id IN: setGcId]){
                decimal newPurchaseCost = 0;
                for(Game_Components__c gc: cgq.Game_Components__r){
                    newPurchaseCost = newPurchaseCost + gc.Component_Purchase_Cost_1__c;
                }
                cgq.Product_Purchase_Cost1__c = newPurchaseCost;
                customGameQuotes.add(cgq);
            }
            if(customGameQuotes.size() > 0){
                update customGameQuotes;
            }
        }*/
    }
    
    /**
     * Method called on after update
     */
    public static void onAfterUpdate(list<Game_Components__c> newRecords, map<Id, Game_Components__c> oldRecordMap) {
        /*set<string> setGcId = new set<string>();
        for(Game_Components__c gc: newRecords){
            if(gc.Custom_Game_Quote__c != null && gc.Component_Purchase_Cost_1__c != null && gc.Component_Purchase_Cost_1__c != oldRecordMap.get(gc.Id).Component_Purchase_Cost_1__c){
                setGcId.add(gc.Custom_Game_Quote__c);
            }
        }
        
        if(setGcId.size() > 0){
            list<Custom_Game_Quote__c> customGameQuotes = new list<Custom_Game_Quote__c>();
            for(Custom_Game_Quote__c cgq: [SELECT Id, Product_Purchase_Cost1__c, (SELECT Component_Purchase_Cost_1__c FROM Game_Components__r) FROM Custom_Game_Quote__c WHERE Id IN: setGcId]){
                decimal newPurchaseCost = 0;
                for(Game_Components__c gc: cgq.Game_Components__r){
                    newPurchaseCost = newPurchaseCost + (gc.Component_Purchase_Cost_1__c != null ? gc.Component_Purchase_Cost_1__c : 0);
                }
                cgq.Product_Purchase_Cost1__c = newPurchaseCost;
                customGameQuotes.add(cgq);
            }
            if(customGameQuotes.size() > 0){
                update customGameQuotes;
            }
        }*/
    }
}