force-app/main/default/objects/AutoNumberConfiguration__c/AutoNumberConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generate Gravity Form Auto Number.</description>
    <label>Auto Number Configuration</label>
</CustomObject>

force-app/main/default/objects/AutoNumberConfiguration__c/fields/Last_Generated_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Generated_Number__c</fullName>
    <label>Last Generated Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Convert_Lead__c/Convert_Lead__c.object-meta.xml
<CustomObject>
    <label>Convert Lead</label>
    <nameField>
        <label>Convert Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Convert Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Convert_Lead__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convert_Lead__c/fields/Reminder_Time__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Time__c</fullName>
    <label>Reminder Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>8:00 AM</fullName>
                <default>true</default>
                <label>8:00 AM</label>
            </value>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convert_Lead__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Convert_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewLeadControllerTest.cls
@isTest(seeAllData=false)
public class NewLeadControllerTest{
    public static testMethod void testNewLeadController(){
        list<AutoNumberConfiguration__c> acs = new list<AutoNumberConfiguration__c>();
        acs.add(new AutoNumberConfiguration__c(Name = 'Others', Last_Generated_Number__c = 0));
        insert acs;
        
        PageReference pageRef = Page.Convert_Lead;
        Test.setCurrentPage(pageRef);
        test.startTest();        
        Lead ld = new Lead (Firstname='testfn', Lastname='testln', Company='ABC Comp.', Status='Open', LeadSource='Site Sample Packet Request'); 
        insert ld;
        
        ApexPages.currentPage().getParameters().put('id',ld.Id);
        NewLeadController controller=new NewLeadController();        
        controller.hidden_convert_status='1';
        controller.convert_Lead=new Convert_Lead__c();
        controller.convert_Lead.User__c= UserInfo.getUserId();
        controller.convert_Lead.Reminder_Date__c=System.now().date();
        controller.convert_Lead.Reminder_Time__c='07:00 AM';
        controller.convert_Lead.Opportunity_Name__c='Doomstone';
        controller.hidden_account='000000000000000';
        controller.accnt='000000000000000';
        PageReference pref=controller.convertLead();
        //String nextPage = controller.convertLead().getUrl();
        
        // Verify that the success page displays
        //System.assertEquals('/apex/success', nextPage);
        test.stopTest();        
    }
}