force-app/main/default/objects/AWS_File__c/AWS_File__c.object-meta.xml
<CustomObject>
    <label>AWS File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AWS_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <inlineHelpText>Full Name of the file</inlineHelpText>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/fields/Task_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Task_Record_ID__c</fullName>
    <label>Task Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/fields/Task_Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Record_Name__c</fullName>
    <label>Task Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <formula>HYPERLINK(&apos;/lightning/n/CMT_DocumentView?c__s3fileId=&apos;+ External_ID__c ,  File_Name__c , &apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>View</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CMT_TaskListLWC.cls
/**
 * @description       : 
 * @author            : Ashwani Soni
 * @group             : 
 * @last modified on  : 07-19-2021
 * @last modified by  : Ashwani Soni
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   06-29-2021   Ashwani Soni   Initial Version
**/
public with sharing class CMT_TaskListLWC 
{
    @AuraEnabled
    public static List<AWS_File__c> getTaskFileData(String recordId)
    {
        return [SELECT Id, File_Name__c, Task_Record_Name__c, External_ID__c, Task_Record_ID__c, View__c, CreatedDate FROM AWS_File__c WHERE Task_Record_ID__c =:recordId];
    }

}